steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/calories-nextjs/calories-nextjs-docker-repo/calories-nextjs-docker-image:tag1', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/calories-nextjs/calories-nextjs-docker-repo/calories-nextjs-docker-image:tag1']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'calories-nextjs-docker-image', '--image', 'asia-east1-docker.pkg.dev/calories-nextjs/calories-nextjs-docker-repo/calories-nextjs-docker-image:tag1', '--region', 'asia-east1']
images:
- 'asia-east1-docker.pkg.dev/calories-nextjs/calories-nextjs-docker-repo/calories-nextjs-docker-image:tag1'
